# Site settings
title: Francis Pires
email: fracispires@msn.com
twitter_username: fransql
github_username: francispires
intro: Desenvolvendo-se desenvolvendo
subintro: Bem vindo ao meu site, sinta-se Ã  vontade
category-list: [fia, fiap, musica, math, games, madeirada]
# Build settings
markdown: kramdown
